---
title: "ic-ggplot2-tutorials"
author: "Ryan Richardson"
date: "05/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaicData)
library(ggplot2)
library(gridExtra)
library(plyr)
```

## 1-3

```{r carsMpg}
summary(mtcars)
summary(SnowGR)
mpgHist = ggplot(mtcars, aes(x=mpg)) + geom_histogram(color="black", fill="yellow", alpha=0.3)
mpgHist

mpgDensity = ggplot(mtcars, aes(x=mpg, y = ..density..)) + geom_histogram(color="black", fill="yellow", alpha=0.3) + geom_density(color = "cyan", fill = "cyan", alpha = 0.2) 
mpgDensity

mpgDensityMode =  ggplot(mtcars, aes(x=mpg, y = ..density..)) + geom_histogram(color="black", fill="yellow", alpha=0.3) + geom_density(color = "cyan", fill = "cyan", alpha = 0.2) + geom_hline(yintercept = 0.068)
mpgDensityMode

mtcars$am = as.factor(mtcars$am)
mtcars$am = revalue(mtcars$am, c("0"="A", "1"="M"))
mpgAuto = ggplot(mtcars, aes(x=mpg, y = ..density..)) + geom_density(aes(group = am, color = am)) 
mpgAuto
```

## 4


```{r carsQsec}
mpgQsec = ggplot(mtcars, aes(x=mpg, y = qsec)) + geom_point(color="blue") + labs(title="A")

mpgQsecDrat = ggplot(mtcars, aes(x=mpg, y = qsec)) + geom_point(aes(color = drat))  + labs(title="B")

mpgQsecNumeric = ggplot(mtcars, aes(x=mpg, y = qsec)) + geom_point(aes(color = as.numeric(am)))  + labs(title="C")

mpgQsecTransmission = ggplot(mtcars, aes(x=mpg, y = qsec)) + geom_point(aes(color = am))  + labs(title="D")

grid.arrange(mpgQsec, mpgQsecDrat, mpgQsecNumeric, mpgQsecTransmission, nrow = 2)
```

## 5

```{r customFillQsec}

mpgQsecCustom = ggplot(mtcars, aes(x=mpg, y = qsec)) + 
  geom_point(aes(color = am, fill=am, shape=am), size=2)  + 
  scale_color_manual(values=c("magenta","blue")) + 
  scale_shape_manual(values=c(16,24)) +
  scale_fill_manual(values=c("magenta","blue")) +
  labs(color="Transmission Type", shape = "Transmission Type", fill = "Transmission Type", x ="MPG", y="Quarter Mile Time (sec)") +
  theme(legend.position = c(0.7, 0.8), legend.direction = "horizontal", axis.title = element_text(size = 12))
mpgQsecCustom
ggsave("transmissionType.png", plot = mpgQsecCustom, device="png")
```
